# Test 

In [4]:
import torch
import torch_geometric
from torch_geometric.datasets import Planetoid
import torch_geometric.utils as pygu

In [22]:
dataset = Planetoid(root="Testnb",name= "Cora")
print(dataset)
print("number of graphs:\t\t",len(dataset))
print("number of classes:\t\t",dataset.num_classes)
print("number of node features:\t",dataset.num_node_features)
print("number of edge features:\t",dataset.num_edge_features)

Cora()
number of graphs:		 1
number of classes:		 7
number of node features:	 1433
number of edge features:	 0


In [4]:
print(dataset.data)

Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])


/opt/anaconda3/envs/testNeuro/lib/python3.11/site-packages/torch_geometric/data/in_memory_dataset.py:300: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  warnings.warn(msg)


In [3]:
import torch_geometric.utils as pygu
pygu.contains_self_loops(dataset.edge_index)

NameError: name 'dataset' is not defined

In [6]:
dataset.edge_index[:,:10]

tensor([[ 633, 1862, 2582,    2,  652,  654,    1,  332, 1454, 1666],
        [   0,    0,    0,    1,    1,    1,    2,    2,    2,    2]])

In [7]:
dataset.x

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [12]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]])
print(x)
print(x.dim())
print("0")
print(x.unsqueeze(0))
print("1")
print(x.unsqueeze(1))
print("-1 = 2")
print(x.unsqueeze(-1))
print("0 + -1")
print(x.unsqueeze(0).unsqueeze(-1))


tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
2
0
tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]]])
1
tensor([[[1, 2, 3, 4]],

        [[5, 6, 7, 8]]])
-1 = 2
tensor([[[1],
         [2],
         [3],
         [4]],

        [[5],
         [6],
         [7],
         [8]]])
0 + -1
tensor([[[[1],
          [2],
          [3],
          [4]],

         [[5],
          [6],
          [7],
          [8]]]])


In [20]:
x = torch.tensor([1,2,3,4]).unsqueeze(1)
print(x)
print("cat without dimension : ", torch.cat((x,x)))
torch.cat((x,x),1)

tensor([[1],
        [2],
        [3],
        [4]])
cat without dimension :  tensor([[1],
        [2],
        [3],
        [4],
        [1],
        [2],
        [3],
        [4]])


tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [6]:
from models.NM import NeuroMatchNetwork 
from torch_geometric.datasets import TUDataset
dataset = TUDataset(root="/tmp/ENZYMES", name="ENZYMES")
testNMN = NeuroMatchNetwork()
print(testNMN)

NeuroMatchNetwork(
  (pre_mp): Sequential(
    (0): Linear(in_features=1, out_features=64, bias=True)
  )
  (convs): ModuleList(
    (0): SAGEConv(64, 64, aggr=sum)
    (1): SAGEConv(128, 64, aggr=sum)
    (2): SAGEConv(192, 64, aggr=sum)
    (3): SAGEConv(256, 64, aggr=sum)
    (4): SAGEConv(320, 64, aggr=sum)
    (5): SAGEConv(384, 64, aggr=sum)
    (6): SAGEConv(448, 64, aggr=sum)
    (7): SAGEConv(512, 64, aggr=sum)
  )
  (post_mp): Sequential(
    (0): Linear(in_features=576, out_features=64, bias=True)
    (1): Dropout(p=0.0, inplace=False)
    (2): LeakyReLU(negative_slope=0.1)
    (3): Linear(in_features=64, out_features=64, bias=True)
    (4): ReLU()
    (5): Linear(in_features=64, out_features=256, bias=True)
    (6): ReLU()
    (7): Linear(in_features=256, out_features=64, bias=True)
  )
)


In [14]:
import networkx as nx 
import random
from tqdm import tqdm
train_len = int(0.8 * len(dataset))
train, test = [], []
dataset = list(dataset)
print(dataset)
random.shuffle(dataset)
print(dataset)
has_name = hasattr(dataset[0], "name")
print(has_name)
print(type(dataset))
for i, graph in tqdm(enumerate(dataset)):
    if not type(graph) == nx.Graph:
        if has_name: del graph.name
        graph = pygu.to_networkx(graph).to_undirected()
    if i < train_len:
        train.append(graph)
    else:
        test.append(graph)

[Data(edge_index=[2, 190], x=[45, 3], y=[1]), Data(edge_index=[2, 158], x=[38, 3], y=[1]), Data(edge_index=[2, 190], x=[51, 3], y=[1]), Data(edge_index=[2, 60], x=[17, 3], y=[1]), Data(edge_index=[2, 70], x=[18, 3], y=[1]), Data(edge_index=[2, 190], x=[51, 3], y=[1]), Data(edge_index=[2, 86], x=[24, 3], y=[1]), Data(edge_index=[2, 170], x=[44, 3], y=[1]), Data(edge_index=[2, 94], x=[27, 3], y=[1]), Data(edge_index=[2, 100], x=[21, 3], y=[1]), Data(edge_index=[2, 178], x=[48, 3], y=[1]), Data(edge_index=[2, 70], x=[19, 3], y=[1]), Data(edge_index=[2, 92], x=[22, 3], y=[1]), Data(edge_index=[2, 182], x=[45, 3], y=[1]), Data(edge_index=[2, 156], x=[48, 3], y=[1]), Data(edge_index=[2, 232], x=[52, 3], y=[1]), Data(edge_index=[2, 134], x=[30, 3], y=[1]), Data(edge_index=[2, 66], x=[19, 3], y=[1]), Data(edge_index=[2, 100], x=[22, 3], y=[1]), Data(edge_index=[2, 176], x=[40, 3], y=[1]), Data(edge_index=[2, 166], x=[43, 3], y=[1]), Data(edge_index=[2, 46], x=[11, 3], y=[1]), Data(edge_index=[

600it [00:00, 1317.62it/s]


In [16]:
train[:2]